name: aoes
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab=1.2.5
  - jupyter_client=5.3.1
  - nbserverproxy
  - netcdf4=1.5.1.1
  - metpy
  - numpy
  - scipy
  - xarray>=0.14.1
  - dask
  - xskillscore>=0.0.12
  - cartopy
  - matplotlib
  - pip
  - pip:
      - git+https://github.com/bradyrx/climpred
